export const PostApprovalStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

export const PostCategoriesEnum = [
  { value: "common", label: "common" },
  { value: "ആക്ഷൻ", label: "ആക്ഷൻ" },
  { value: "അമ്മായിഅമ്മ", label: "അമ്മായിഅമ്മ" },
  { value: "ആന്റി കഥകൾ", label: "ആന്റി കഥകൾ" },
  { value: "ചേച്ചി കഥകൾ", label: "ചേച്ചി കഥകൾ" },
  { value: "ചെറുകഥകൾ", label: "ചെറുകഥകൾ" },
  { value: "സിനിമ കമ്പികഥകൾ", label: "സിനിമ കമ്പികഥകൾ" },
  { value: "ക്രൈം ത്രില്ലെർ", label: "ക്രൈം ത്രില്ലെർ" },
  { value: "ഇംഗ്ലീഷ് നോവൽസ്", label: "ഇംഗ്ലീഷ് നോവൽസ്" },
  { value: "എന്റർടൈൻമെന്റ്", label: "എന്റർടൈൻമെന്റ്" },
  { value: "ഫാമിലി", label: "ഫാമിലി" },
  { value: "ഹൊറർ ഫിക്ഷൻ", label: "ഹൊറർ ഫിക്ഷൻ" },
  { value: "കഥകൾ", label: "കഥകൾ" },
  { value: "കമ്പി കാർട്ടൂൺ", label: "കമ്പി കാർട്ടൂൺ" },
  { value: "കമ്പി ഗെയിംസ്", label: "കമ്പി ഗെയിംസ്" },
  { value: "കമ്പി ജോക്സ്", label: "കമ്പി ജോക്സ്" },
  { value: "കമ്പി ന്യൂസ്‌", label: "കമ്പി ന്യൂസ്‌" },
  { value: "കമ്പി നോവൽസ്", label: "കമ്പി നോവൽസ്" },
  { value: "കമ്പി പാട്ടുകൾ", label: "കമ്പി പാട്ടുകൾ" },
  { value: "കമ്പി ഫോൺ", label: "കമ്പി ഫോൺ" },
  { value: "കമ്പി ടീച്ചർ", label: "കമ്പി ടീച്ചർ" },
  { value: "കമ്പികഥകൾ", label: "കമ്പികഥകൾ" },
  { value: "കമ്പികഥകൾ ഓഡിയോ",label: "കമ്പികഥകൾ ഓഡിയോ" },
  { value: "കമ്പികഥകൾ PDF",label: "കമ്പികഥകൾ PDF"},
  { value: "കമ്പിപടം",label: "കമ്പിപടം"},
  { value: "ലവ് സ്റ്റോറീസ്",label: "ലവ് സ്റ്റോറീസ്" },
  { value: "PDF കമ്പി കഥകൾ",label: "PDF കമ്പി കഥകൾ" },
  { value: "അവിഹിതം",label: "അവിഹിതം" },
  { value: "ഇറോട്ടിക് ലവ് സ്റ്റോറീസ്",label: "ഇറോട്ടിക് ലവ് സ്റ്റോറീസ്" },
  { value: "ഒളിഞ്ഞ് നോട്ടം",label: "ഒളിഞ്ഞ് നോട്ടം" },
  { value: "കുക്കോൾഡ്",label: "കുക്കോൾഡ്" },
  { value: "കൗമാരം",label: "കൗമാരം" },
  { value: "ഗേ",label: "ഗേ" },
  { value: "ചീറ്റിംഗ്",label: "ചീറ്റിംഗ്" },
  { value: "നിഷിദ്ധ സംഗമം",label: "നിഷിദ്ധ സംഗമം" },
  { value: "ഫാന്റസി",label: "ഫാന്റസി" },
  { value: "ഫെംഡം",label: "ഫെംഡം" },
  { value: "ഫെറ്റിഷ്",label: "ഫെറ്റിഷ്" },
  { value: "മന്മഥം",label: "മന്മഥം" },
  { value: "രതിഅനുഭവങ്ങൾ",label: "രതിഅനുഭവങ്ങൾ" },
  { value: "റിയൽ കഥകൾ",label: "റിയൽ കഥകൾ" },
  { value: "ലെസ്ബിയൻ",label: "ലെസ്ബിയൻ" },
  { value: "സംഘം ചേർന്ന്",label: "സംഘം ചേർന്ന്" },
];
